/** Matches the video ID out of youtube.com/watch, youtube.com/embed, youtube.com/shorts, and youtu.be URLs. */
const YOUTUBE_ID_PATTERN = /(?:youtube(?:-nocookie)?\.com\/(?:watch\?(?:.*&)?v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/;

export function extractYouTubeId(url: string): string | null {
  return url.match(YOUTUBE_ID_PATTERN)?.[1] ?? null;
}

export function isYouTubeLink(url: string): boolean {
  return extractYouTubeId(url) !== null;
}

/** `hqdefault` is always generated by YouTube (unlike `maxresdefault`, which is missing for some videos). */
export function youTubeThumbnailUrl(videoId: string): string {
  return `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
}

export function youTubeEmbedUrl(videoId: string): string {
  return `https://www.youtube.com/embed/${videoId}`;
}
